apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
      app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
        - name: myjavaapp-container
          image: manju416/myjavaapp15jan:1
          ports:
            - containerPort: 8080